### ISSUE TITLE
HQ Detection doesn't work / I want to undercut HQ only when listing HQ

### ISSUE THREAD

**Issue by tesu** [tesu/PennyPincher#13]
Below are two instances where an NQ item is being listed but Penny Pincher thinks it is HQ (sourced from #plugin-testing).
![image](https://user-images.githubusercontent.com/840752/123334826-a5567880-d511-11eb-9519-6c4317add818.png)
![image](https://user-images.githubusercontent.com/840752/123334840-aa1b2c80-d511-11eb-8529-618223cc2c97.png)

>  it seems to happen while listing, not while adjusting prices of items that are already listed

@Looty can you figure out what's wrong? Maybe there are two different offsets needed here, one for listing new items and another (the current one) for updating listed items.

**Comment by Looty** [comment]
Seems like this happens whenever the user hovers over a different item than was listed- it'll take into account the last item that was hovered on

It looks like the tooltip method is not a guarantee 
I'll lookout for another method

**Comment by gucciBane** [comment]
Just noting that I'm experiencing this frequently. Having /penny hq enabled doesn't seem to be making a difference.

**Comment by tesu** [comment]
@Looty are you still working on this? If not, I'll just revert to the old method of just always undercutting HQ price regardless of HQ status of the item being listed.

**Comment by Looty** [comment]
Haven't found a solution for this yet..
you can revert

**Comment by tesu** [comment]
Resolved by #41
