### ISSUE TITLE
Penny Pitcher broken after 5.58 patch

### ISSUE THREAD

**Issue by RyanBlazee** [tesu/PennyPincher#14]
I have removed and reinstalled the plugin but it is not responding.

**Comment by n3farious** [comment]
Same issue. Additionally, tried to toggle all of the parameters to no avail.

**Comment by n3farious** [comment]
> I have removed and reinstalled the plugin but it is not responding.

I just deleted my comment. See pinned issue #12, as this solves the problem. You may want to close your issue after verifying that the forced download fixes for you as well.

**Comment by Acederp** [comment]
I have also have problems with penny pincher today. :petthetesu:

**Comment by tesu** [comment]
dupe of #12
