### ISSUE TITLE
[Feature Request] HQ/NQ matching item to list

### ISSUE THREAD

**Issue by SilentSigns** [tesu/PennyPincher#17]
Hi, I am really enjoying this addon however I am having trouble incorporating it into my workflow when I am trying to sell both NQ intermediary crafts [Star Quartz], and HQ final crafts [Blue Zircon Bracelet of Healing].

When I am listing my HQ crafts I am wanting to compete with others so am using the "only undercut HQ items" option. However this creates a problem for my NQ crafts for which a HQ exists, I just want to undercut the market but instead it's trying to compete with HQ's at a much higher price point. I considered turning this off but then I lose my protection against aggresive NQ undercuts in HQ markets.

Would an options to match price check quality with the item that is being listed be possible?

**Comment by tesu** [comment]
This existed as an option during testing at one point, but it didn't work all the time (#13). If/when that's fixed, the option will return.

**Comment by zandzpider** [comment]
> This existed as an option during testing at one point, but it didn't work all the time (#13). If/when that's fixed, the option will return.

Would you mind telling me what you did to do this?
I tried to see the item that was put for sale, but i didn't get anywhere with it sadly to achieve this

**Comment by tesu** [comment]
#7
