### ISSUE TITLE
Implement option to copy HQ price only when selling an HQ item

### ISSUE THREAD

**Issue by AlexSkylark** [tesu/PennyPincher#19]
This would be the thing to make this addon perfect <3

Most of the times you want to sell HQ items, but on the occasions where the item you have is NQ, you find yourself still needing to set prices manually. Is this doable? :)

**Comment by ividyon** [comment]
Heavily agreed. The HQ price should only be copied when you're trying to sell an HQ item.

**Comment by tesu** [comment]
As mentioned in #17,

> This existed as an option during testing at one point, but it didn't work all the time (#13). If/when that's fixed, the option will return.
