### ISSUE TITLE
Let me copy prices from the Market Board Plugin

### ISSUE THREAD

**Issue by aeroncastle** [tesu/PennyPincher#22]
I love the idea of this plugin but i have almost no use for it because when i sell things i want to be the cheapest that i can be and sell the fastest or i end up with my retainers full and being the cheapest in my specific server is not enough, things still take days to sell plz let me copy prices -1 from the Market Board Plugin. love you guys, ty for everyting

**Comment by tesu** [comment]
This makes more sense as a marketboard plugin request, which I see you've already made at https://github.com/fmauNeko/MarketBoardPlugin/issues/29.

**Comment by aeroncastle** [comment]
well, its true, i just wish they cared about the functionality as someone from this plugin could...
