### ISSUE TITLE
[Feature Request] Exclude your own retainers from pinching

### ISSUE THREAD

**Issue by OneCrazyRussian** [tesu/PennyPincher#37]
As a Lala, I often find myself manipulating the market by using same items on multiple retainers. And I'd like to not include my retainers into pennypinching calculations

As-is: your own retainers are pinched if you sell same item on multiple retainers
To-be: option to exclude own retainers (or a manual exclusion retainer name list)

**Comment by tesu** [comment]
Someone tried to add this a while back (#6), but the code quality wasn't great so it didn't get merged. Feel free to revive it.

**Comment by tesu** [comment]
Resolved by #42
