### ISSUE TITLE
Lowest price getting copied even if just viewing the marketboard normally (not via retainer)

### ISSUE THREAD

**Issue by Looty** [tesu/PennyPincher#8]
Hey!

Is this intended?
From my understanding, if I want to get the lowest price - I only want it whenever I use my retainer **to sell something**?

Getting the same result with the version before the update today
* /penny smart doesn't do anything regarding this

**Comment by tesu** [comment]
Do you have `/penny` toggled on? It should be toggled off (with `/penny smart` on) if you want to only copy from retainer

**Comment by Looty** [comment]
Ohh I see

Thanks!!
